# Application properties for the idempotency-core module
spring.application.name=idempotency-core
server.port=8080


idempotency.storage.type=redis
# idempotency.storage.type=memory

#  Default TTL for idempotency keys in seconds (1 hour)
idempotency.default-ttl=3600

# Redis configuration - replace with your actual Redis connection details
spring.data.redis.host=my-host
spring.data.redis.port=my-port
spring.data.redis.password=my-password


# This lets you see the AOP and Redis logs in the console
logging.level.com.byteentropy.idempotency_core=DEBUG